openaiBaseApiUrl: http://ray-serve-llm-serve-svc:8000/v1
ollama:
  enabled: false
pipelines:
  enabled: false

extraEnvVars:
  - name: ENABLE_ADMIN_CHAT_ACCESS
    value: "False"
  - name: ENABLE_ADMIN_EXPORT
    value: "False"