name: Testing Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  VERSION: 0.0.0-testing-20260125125844
  ZONE_NAME: test.mithrilsecurity.io
  AZURE_GALLERY_ID: "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/fluorite-azure-registries/providers/Microsoft.Compute/galleries/FluoriteGallery/images"

jobs:
  test-nginx-self-ca:
    runs-on: fluorite-runner
    timeout-minutes: 60
    env:
      PACKAGE: nginx-self-ca
      AZURE_CONFIG_DIR: /home/ubuntu/.azure-${{ github.job }}
    steps:
      - name: Set Hostname
        run: |
          echo "HOSTNAME=${{ github.job }}.${{ env.ZONE_NAME }}" >> $GITHUB_ENV
          VERSION_FORMATTED="${VERSION//./-}"
          echo "AZURE_IMAGE=${{ env.AZURE_GALLERY_ID }}/fluorite-os-${VERSION_FORMATTED}/versions/1.0.0" >> $GITHUB_ENV
          echo "AZURE_IMAGE_GPU=${{ env.AZURE_GALLERY_ID }}/fluorite-os-with-gpu-${VERSION_FORMATTED}/versions/1.0.0" >> $GITHUB_ENV

          mkdir -p "${{ github.workspace }}/${{ github.job }}"
          echo "DIR=${{ github.workspace }}/${{ github.job }}" >> $GITHUB_ENV

      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.16

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build provisioning bundle
        run: earthly --strict -P  +zarf-${{ env.PACKAGE }}

      - name: Run setup build step
        run: |
          # Get the this version's gcp_notarizer_measurements.json 
          curl "https://storage.googleapis.com/fluorite/${{ env.VERSION }}/gcp-cvm-notarizer/gcp_notarizer_measurements.json" > libraries/attestation/gcp-shielded-vm-attestation/gcp_notarizer_measurements.json
                    
          earthly --strict -P  +setup

      - name: Generate Operator Certificates
        run: |
          ./operator/generate-certificates-cli/target/release/generate-certificates-cli --force --cert-directory-path ${{ env.DIR }}/certificates

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Inject variables in the job environment
        run: |
          # Get the latest FluoriteOS image published on Azure Image Gallery and it's PCR4 Golden Value
          MEASUREMENT_URL="https://storage.googleapis.com/fluorite/${{ env.VERSION }}/fluorite-os/cloud-vtpm/os-measurement.json"
          OS_MEASUREMENT=$(curl $MEASUREMENT_URL | jq -r .fluoriteos_pcr4)
          echo "OS_MEASUREMENT=$OS_MEASUREMENT" >> $GITHUB_ENV

          PLATFORM_MEASUREMENTS_PATH="./measurements/measurements_azure.json"
          echo "PLATFORM_MEASUREMENTS_PATH=$PLATFORM_MEASUREMENTS_PATH" >> $GITHUB_ENV

          PACKAGE_PATH="./packages/zarf-package-${{ env.PACKAGE }}-amd64-1.0.0.tar.zst"
          echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV

          # Compute the hash of the provisioning package
          BUNDLE_HASH=$(sha256sum $PACKAGE_PATH | awk '{print $1}')
          echo "BUNDLE_HASH=$BUNDLE_HASH" >> $GITHUB_ENV

          OPERATOR_CERTIFICATE_PATH="${{ env.DIR }}/certificates/cert.pem"
          echo "OPERATOR_CERTIFICATE_PATH=$OPERATOR_CERTIFICATE_PATH" >> $GITHUB_ENV

          OPERATOR_PRIVATE_KEY_PATH="${{ env.DIR }}/certificates/key.pem"
          echo "OPERATOR_PRIVATE_KEY_PATH=$OPERATOR_PRIVATE_KEY_PATH" >> $GITHUB_ENV

          # Encode the operator certificate for the next jobs
          OPERATOR_CERTIFICATE_B64=$(base64 -w0 $OPERATOR_CERTIFICATE_PATH)
          echo "OPERATOR_CERTIFICATE_B64=$OPERATOR_CERTIFICATE_B64" >> $GITHUB_ENV

          DEPLOYMENT_CONFIG_PATH="${{ env.DIR }}/deployment_config.yaml"
          echo "DEPLOYMENT_CONFIG_PATH=$DEPLOYMENT_CONFIG_PATH" >> $GITHUB_ENV

          ATTESTATION_BACKEND="AzureTrustedLaunchVM"
          echo "ATTESTATION_BACKEND=$ATTESTATION_BACKEND" >> $GITHUB_ENV

      - name: Create deployment config file
        run: |
          cat << EOF > ${{ env.DEPLOYMENT_CONFIG_PATH }}
          package:
            deploy:
              set:
          EOF

          yq -iy '.package.deploy.set.HOSTNAME = "${{ env.HOSTNAME }}"' ${{ env.DEPLOYMENT_CONFIG_PATH }}

      - name: Spawn VMs for test
        working-directory: operator/vm-cli/
        run: |

          uv sync --locked --all-extras --dev
          uv run main.py \
            --location francecentral \
            --resource-group-name "EndToEndTest-${{ github.job }}" \
            --vm-type Standard_D4as_v4 \
            --num-control-plane-nodes 1 \
            --num-agent-nodes 1 \
            --operator-pem-cert-path ${{ env.OPERATOR_CERTIFICATE_PATH }} \
            --vm-security-type TrustedLaunch \
            --image-resource-id "${{ env.AZURE_IMAGE }}" \
            --output-path ${{ env.DIR }}/cluster.json

      - name: Create A record for master VM
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            RESOURCE_GROUP="ivan-fli-multinode"            
            A_RECORD_NAME="${{ github.job }}"
            MASTER_IP=$(az vm list-ip-addresses -g "EndToEndTest-${{ github.job }}" -n master-vm --query "[].virtualMachine.network.publicIpAddresses[0].ipAddress" -o tsv)

            # Add the A record for the master vm
            az network dns record-set a add-record \
              --resource-group $RESOURCE_GROUP \
              --zone-name ${{ env.ZONE_NAME }} \
              --record-set-name $A_RECORD_NAME \
              --ipv4-address $MASTER_IP  \
              --ttl 3600

      - name: Build CLI tools
        run: earthly --strict -P  +operator-cli

      - name: Provision VMs
        run: |
          ./operator/operator-cli/target/release/operator-cli \
            --zarf-package-path ${{ env.PACKAGE_PATH }} \
            --os-measurement ${{ env.OS_MEASUREMENT }} \
            --platform-measurements-path ${{ env.PLATFORM_MEASUREMENTS_PATH }} \
            --operator-cert-path ${{ env.OPERATOR_CERTIFICATE_PATH }} \
            --operator-private-key-path ${{ env.OPERATOR_PRIVATE_KEY_PATH }} \
            --cluster-file-path ${{ env.DIR }}/cluster.json \
            --deployment-config-path ${{ env.DEPLOYMENT_CONFIG_PATH }} \
            --attestation-backend ${{ env.ATTESTATION_BACKEND }}

      - name: Build Client app
        run: earthly --strict -P  +client

      - name: Run client app
        run: |

          echo "Wait for DNS to propagate" && sleep 120

          ./multinode-provisioning/examples/client/target/release/client \
            --master-url "https://${{ env.HOSTNAME }}" \
            --operator-certificate-path ${{ env.OPERATOR_CERTIFICATE_PATH }} \
            --bundle-hash ${{ env.BUNDLE_HASH }} \
            --os-measurement ${{ env.OS_MEASUREMENT }} \
            --platform-measurements-path ${{ env.PLATFORM_MEASUREMENTS_PATH }}  \
            --attestation-backend ${{ env.ATTESTATION_BACKEND }}

      - name: Delete resource group
        if: always()
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group delete -n "EndToEndTest-${{ github.job }}" --force-deletion-types Microsoft.Compute/virtualMachines --yes
  test-nginx:
    runs-on: fluorite-runner
    timeout-minutes: 60
    env:
      PACKAGE: nginx
      AZURE_CONFIG_DIR: /home/ubuntu/.azure-${{ github.job }}
    steps:
      - name: Set Hostname
        run: |
          echo "HOSTNAME=${{ github.job }}.${{ env.ZONE_NAME }}" >> $GITHUB_ENV
          VERSION_FORMATTED="${VERSION//./-}"
          echo "AZURE_IMAGE=${{ env.AZURE_GALLERY_ID }}/fluorite-os-${VERSION_FORMATTED}/versions/1.0.0" >> $GITHUB_ENV
          echo "AZURE_IMAGE_GPU=${{ env.AZURE_GALLERY_ID }}/fluorite-os-with-gpu-${VERSION_FORMATTED}/versions/1.0.0" >> $GITHUB_ENV

          mkdir -p "${{ github.workspace }}/${{ github.job }}"
          echo "DIR=${{ github.workspace }}/${{ github.job }}" >> $GITHUB_ENV

      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.16

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build provisioning bundle
        run: earthly --strict -P  +zarf-${{ env.PACKAGE }}

      - name: Run setup build step
        run: |
          # Get the this version's gcp_notarizer_measurements.json 
          curl "https://storage.googleapis.com/fluorite/${{ env.VERSION }}/gcp-cvm-notarizer/gcp_notarizer_measurements.json" > libraries/attestation/gcp-shielded-vm-attestation/gcp_notarizer_measurements.json
                    
          earthly --strict -P  +setup

      - name: Generate Operator Certificates
        run: |
          ./operator/generate-certificates-cli/target/release/generate-certificates-cli --force --cert-directory-path ${{ env.DIR }}/certificates

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Inject variables in the job environment
        run: |
          # Get the latest FluoriteOS image published on Azure Image Gallery and it's PCR4 Golden Value
          MEASUREMENT_URL="https://storage.googleapis.com/fluorite/${{ env.VERSION }}/fluorite-os/cloud-vtpm/os-measurement.json"
          OS_MEASUREMENT=$(curl $MEASUREMENT_URL | jq -r .fluoriteos_pcr4)
          echo "OS_MEASUREMENT=$OS_MEASUREMENT" >> $GITHUB_ENV

          PLATFORM_MEASUREMENTS_PATH="./measurements/measurements_azure.json"
          echo "PLATFORM_MEASUREMENTS_PATH=$PLATFORM_MEASUREMENTS_PATH" >> $GITHUB_ENV

          PACKAGE_PATH="./packages/zarf-package-${{ env.PACKAGE }}-amd64-1.0.0.tar.zst"
          echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV

          # Compute the hash of the provisioning package
          BUNDLE_HASH=$(sha256sum $PACKAGE_PATH | awk '{print $1}')
          echo "BUNDLE_HASH=$BUNDLE_HASH" >> $GITHUB_ENV

          # Generate the password for the Attestation Transparency Service
          ATS_PASSWORD=$(openssl rand -hex 32)
          echo "::add-mask::$ATS_PASSWORD"        
          echo "ATS_PASSWORD=$ATS_PASSWORD" >> $GITHUB_ENV

          OPERATOR_CERTIFICATE_PATH="${{ env.DIR }}/certificates/cert.pem"
          echo "OPERATOR_CERTIFICATE_PATH=$OPERATOR_CERTIFICATE_PATH" >> $GITHUB_ENV

          OPERATOR_PRIVATE_KEY_PATH="${{ env.DIR }}/certificates/key.pem"
          echo "OPERATOR_PRIVATE_KEY_PATH=$OPERATOR_PRIVATE_KEY_PATH" >> $GITHUB_ENV

          # Encode the operator certificate for the next jobs
          OPERATOR_CERTIFICATE_B64=$(base64 -w0 $OPERATOR_CERTIFICATE_PATH)
          echo "OPERATOR_CERTIFICATE_B64=$OPERATOR_CERTIFICATE_B64" >> $GITHUB_ENV

          DEPLOYMENT_CONFIG_PATH="${{ env.DIR }}/deployment_config.yaml"
          echo "DEPLOYMENT_CONFIG_PATH=$DEPLOYMENT_CONFIG_PATH" >> $GITHUB_ENV

          ATS_ENDPOINT="https://ats.${{ github.job }}.${{ env.HOSTNAME }}/verify_csr"
          echo "ATS_ENDPOINT=$ATS_ENDPOINT" >> $GITHUB_ENV

          ATS_CONTAINER_APP_NAME="ats-app-${{ github.job }}"
          echo "ATS_CONTAINER_APP_NAME=$ATS_CONTAINER_APP_NAME" >> $GITHUB_ENV

          ATS_CONTAINER_APP_ENVIRONMENT="ats-env-${{ github.job }}"
          echo "ATS_CONTAINER_APP_ENVIRONMENT=$ATS_CONTAINER_APP_ENVIRONMENT" >> $GITHUB_ENV

          DOMAIN_MONITOR_CONTAINER_APP_NAME="dom-mon-app-${{ github.job }}"
          echo "DOMAIN_MONITOR_CONTAINER_APP_NAME=$DOMAIN_MONITOR_CONTAINER_APP_NAME" >> $GITHUB_ENV

          DOMAIN_MONITOR_CONTAINER_APP_ENVIRONMENT="dom-mon-env-${{ github.job }}"
          echo "DOMAIN_MONITOR_CONTAINER_APP_ENVIRONMENT=$DOMAIN_MONITOR_CONTAINER_APP_ENVIRONMENT" >> $GITHUB_ENV

          RESOURCE_GROUP="ivan-fli-multinode"
          echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> $GITHUB_ENV

          ATTESTATION_BACKEND="AzureTrustedLaunchVM"
          echo "ATTESTATION_BACKEND=$ATTESTATION_BACKEND" >> $GITHUB_ENV

      - name: Create deployment config file
        run: |
          cat << EOF > ${{ env.DEPLOYMENT_CONFIG_PATH }}
          package:
            deploy:
              set:
          EOF

          yq -iy '.package.deploy.set.HOSTNAME = "${{ env.HOSTNAME }}"' ${{ env.DEPLOYMENT_CONFIG_PATH }}
          yq -iy '.package.deploy.set.ATS_PASSWORD = "${{ env.ATS_PASSWORD }}"' ${{ env.DEPLOYMENT_CONFIG_PATH }}
          yq -iy '.package.deploy.set.PUBLIC_CA_KEY = "${{ secrets.PUBLIC_CA_KEY }}"' ${{ env.DEPLOYMENT_CONFIG_PATH }}
          yq -iy '.package.deploy.set.PUBLIC_CA_EMAIL = "${{ secrets.PUBLIC_CA_EMAIL }}"' ${{ env.DEPLOYMENT_CONFIG_PATH }}
          yq -iy '.package.deploy.set.ATS_ENDPOINT = "${{ env.ATS_ENDPOINT }}"' ${{ env.DEPLOYMENT_CONFIG_PATH }}

      - name: Build and deploy Attestation Transparency Service Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: attestation-transparency-service/Dockerfile
          imageToBuild: mycr32671.azurecr.io/attestation-transparency-service-image:latest
          acrName: mycr32671
          acrUsername: mycr32671
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: ${{ env.ATS_CONTAINER_APP_NAME }}
          containerAppEnvironment: ${{ env.ATS_CONTAINER_APP_ENVIRONMENT }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          location: francecentral
          ingress: external
          targetPort: 8000
          disableTelemetry: true
          environmentVariables: >
            PORT="8000" 
            ATTESTATION_BACKEND="${{ env.ATTESTATION_BACKEND }}" 
            PASSWORD="${{ env.ATS_PASSWORD }}"
            OPERATOR_CERTIFICATE_B64="${{ env.OPERATOR_CERTIFICATE_B64 }}"
            BUNDLE_HASH="${{ env.BUNDLE_HASH }}" 
            OS_MEASUREMENT="${{ env.OS_MEASUREMENT }}" 
            RESOURCE_GROUP_NAME="${{ env.RESOURCE_GROUP }}"
            ATTESTATION_STORAGE_ACCOUNT_NAME="attestationproofs"
            STORAGE_URL="https://proof.ivan.mithrilsecurity.io/"
            AZURE_SUBSCRIPTION_ID="${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            IDENTITY_RESOURCE_ID="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/attestation-transparency-service-identity"
            PLATFORM_MEASUREMENTS_PATH="${{ env.PLATFORM_MEASUREMENTS_PATH }}"

      - name: Setup attestation-transparency-service
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            set -euo pipefail

            RESOURCE_GROUP="${{ env.RESOURCE_GROUP }}"
            CONTAINER_APP="${{ env.ATS_CONTAINER_APP_NAME }}"
            CONTAINER_APP_ENV="${{ env.ATS_CONTAINER_APP_ENVIRONMENT }}"

            A_RECORD_NAME="ats.${{ github.job }}"

            # Assign attestation-transparency-service-identity to Container App
            # This is needed because the container needs permission to write to Azure Blob Storage
            az containerapp identity assign \
              --name $CONTAINER_APP \
              --resource-group $RESOURCE_GROUP \
              --user-assigned attestation-transparency-service-identity

            ./scripts/setup-containerapp.sh $RESOURCE_GROUP $CONTAINER_APP $CONTAINER_APP_ENV $ZONE_NAME $A_RECORD_NAME

      - name: Build and deploy domain-monitor Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: domain-monitor/Dockerfile
          imageToBuild: mycr32671.azurecr.io/domain-monitor-image:latest
          acrName: mycr32671
          acrUsername: mycr32671
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: ${{ env.DOMAIN_MONITOR_CONTAINER_APP_NAME }}
          containerAppEnvironment: ${{ env.DOMAIN_MONITOR_CONTAINER_APP_ENVIRONMENT }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          location: francecentral
          ingress: external
          targetPort: 8000
          disableTelemetry: true
          environmentVariables: >
            PORT="8000" 
            ATTESTATION_BACKEND="${{ env.ATTESTATION_BACKEND }}"
            OPERATOR_CERTIFICATE_B64="${{ env.OPERATOR_CERTIFICATE_B64 }}"
            BUNDLE_HASH="${{ env.BUNDLE_HASH }}"
            OS_MEASUREMENT="${{ env.OS_MEASUREMENT }}" 
            STORAGE_URL="https://proof.ivan.mithrilsecurity.io/"
            PLATFORM_MEASUREMENTS_PATH="${{ env.PLATFORM_MEASUREMENTS_PATH }}"
      
      - name: Setup domain-monitor
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            set -euo pipefail

            RESOURCE_GROUP="${{ env.RESOURCE_GROUP }}"
            CONTAINER_APP="${{ env.DOMAIN_MONITOR_CONTAINER_APP_NAME }}"
            CONTAINER_APP_ENV="${{ env.DOMAIN_MONITOR_CONTAINER_APP_ENVIRONMENT }}"
            A_RECORD_NAME="domainmonitor.${{ github.job }}"

            ./scripts/setup-containerapp.sh $RESOURCE_GROUP $CONTAINER_APP $CONTAINER_APP_ENV $ZONE_NAME $A_RECORD_NAME

      - name: Spawn VMs for test
        working-directory: operator/vm-cli/
        run: |

          uv sync --locked --all-extras --dev
          uv run main.py \
            --location eastus2 \
            --resource-group-name "EndToEndTest-${{ github.job }}" \
            --vm-type Standard_D4as_v4 \
            --num-control-plane-nodes 1 \
            --num-agent-nodes 1 \
            --operator-pem-cert-path ${{ env.OPERATOR_CERTIFICATE_PATH }} \
            --vm-security-type TrustedLaunch \
            --image-resource-id "${{ env.AZURE_IMAGE }}" \
            --output-path ${{ env.DIR }}/cluster.json

      - name: Create A record for master VM
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            RESOURCE_GROUP="ivan-fli-multinode"            
            A_RECORD_NAME="${{ github.job }}"
            MASTER_IP=$(az vm list-ip-addresses -g "EndToEndTest-${{ github.job }}" -n master-vm --query "[].virtualMachine.network.publicIpAddresses[0].ipAddress" -o tsv)

            # Add the A record for the master vm
            az network dns record-set a add-record \
              --resource-group $RESOURCE_GROUP \
              --zone-name ${{ env.ZONE_NAME }} \
              --record-set-name $A_RECORD_NAME \
              --ipv4-address $MASTER_IP  \
              --ttl 3600

      - name: Build CLI tools
        run: earthly --strict -P  +operator-cli

      - name: Provision VMs
        run: |
          ./operator/operator-cli/target/release/operator-cli \
            --zarf-package-path ${{ env.PACKAGE_PATH }} \
            --os-measurement ${{ env.OS_MEASUREMENT }} \
            --platform-measurements-path ${{ env.PLATFORM_MEASUREMENTS_PATH }} \
            --operator-cert-path ${{ env.OPERATOR_CERTIFICATE_PATH }} \
            --operator-private-key-path ${{ env.OPERATOR_PRIVATE_KEY_PATH }} \
            --cluster-file-path ${{ env.DIR }}/cluster.json \
            --deployment-config-path ${{ env.DEPLOYMENT_CONFIG_PATH }} \
            --attestation-backend ${{ env.ATTESTATION_BACKEND }}

      - name: Build Client app
        run: earthly --strict -P  +client

      - name: Run client app
        run: |

          echo "Wait for DNS to propagate" && sleep 120

          ./multinode-provisioning/examples/client/target/release/client \
            --master-url "https://${{ env.HOSTNAME }}" \
            --operator-certificate-path ${{ env.OPERATOR_CERTIFICATE_PATH }} \
            --bundle-hash ${{ env.BUNDLE_HASH }} \
            --os-measurement ${{ env.OS_MEASUREMENT }} \
            --platform-measurements-path ${{ env.PLATFORM_MEASUREMENTS_PATH }}  \
            --attestation-backend ${{ env.ATTESTATION_BACKEND }}

      - name: Delete resource group
        if: always()
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group delete -n "EndToEndTest-${{ github.job }}" --force-deletion-types Microsoft.Compute/virtualMachines --yes