name: Testing Pipeline

on:
  workflow_dispatch:

env:
  VERSION: 0.0.0-testing-20260123162349
  ZONE_NAME: test.mithrilsecurity.io
  AZURE_GALLERY_ID: "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/fluorite-azure-registries/providers/Microsoft.Compute/galleries/FluoriteGallery/images"

jobs:
  test_nginx:
    runs-on: self-hosted
    timeout-minutes: 60
    env:
      PACKAGE: nginx-self-ca
    steps:
      - name: Set Hostname
        run: |
          echo "HOSTNAME=${{ github.job }}.${{ env.ZONE_NAME }}" >> $GITHUB_ENV
          VERSION_FORMATTED="${VERSION//./-}"
          echo "AZURE_IMAGE=${{ env.AZURE_GALLERY_ID }}/fluorite-os-${VERSION_FORMATTED}/versions/1.0.0" >> $GITHUB_ENV
          echo "AZURE_IMAGE_GPU=${{ env.AZURE_GALLERY_ID }}/fluorite-os-with-gpu-${VERSION_FORMATTED}/versions/1.0.0" >> $GITHUB_ENV

          mkdir -p "${{ github.workspace }}/${{ github.job }}"
          echo "DIR=${{ github.workspace }}/${{ github.job }}" >> $GITHUB_ENV


      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.16

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build provisioning bundle
        run: earthly --strict -P  +zarf-${{ env.PACKAGE }}

      - name: Calculate Bundle Hash
        id: bundle_hash
        run: |
          BUNDLE_HASH=$(sha256sum ./packages/zarf-package-${{ env.PACKAGE }}-amd64-1.0.0.tar.zst | awk '{print $1}')

          echo "BUNDLE_HASH=$BUNDLE_HASH" >> $GITHUB_OUTPUT # Set an output variable

      - name: Run setup build step
        run: |
          # Get the this version's gcp_notarizer_measurements.json 
          curl "https://storage.googleapis.com/fluorite/${{ env.VERSION }}/gcp-cvm-notarizer/gcp_notarizer_measurements.json" > libraries/attestation/gcp-shielded-vm-attestation/gcp_notarizer_measurements.json
                    
          earthly --strict -P  +setup

      - name: Generate Operator Certificates
        run: |
          ./operator/generate-certificates-cli/target/release/generate-certificates-cli --cert-directory-path ${{ env.DIR }}/certificates

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Create secrets file
        run: |
          sudo apt-get update && sudo apt-get install -y yq


          cat << EOF > ${{ env.DIR }}/deployment_config.yaml
          package:
            deploy:
              set:
          EOF

          yq -iy '.package.deploy.set.HOSTNAME = "${{ env.HOSTNAME }}"' ${{ env.DIR }}/localsecrets$}.yaml

      - name: Get the latest FluoriteOS image published on Azure Image Gallery and it's PCR4 Golden Value
        id: os_image_info
        run: |
          URL="https://storage.googleapis.com/fluorite/${{ env.VERSION }}/fluorite-os/cloud-vtpm/os-measurement.json"
          OS_MEASUREMENT=$(curl $URL | jq -r .fluoriteos_pcr4)
          OPERATOR_CERTIFICATE_B64=$(base64 -w0 ${{ env.DIR }}/certificates/cert.pem)

          echo "OS_MEASUREMENT=$OS_MEASUREMENT" >> $GITHUB_OUTPUT
          echo "OPERATOR_CERTIFICATE_B64=$OPERATOR_CERTIFICATE_B64" >> $GITHUB_OUTPUT

      - name: Build CLI tools
        run: earthly --strict -P  +operator-cli

      - name: Spawn VMs for test
        working-directory: operator/vm-cli/
        run: |

          uv sync --locked --all-extras --dev
          uv run main.py \
            --location francecentral \
            --resource-group-name EndToEndTest-${{ github.job }} \
            --vm-type Standard_NC24ads_A100_v4 \
            --num-control-plane-nodes 1 \
            --num-agent-nodes 1 \
            --operator-pem-cert-path ../.${{ env.DIR }}/certificates/cert.pem \
            --vm-security-type TrustedLaunch \
            --image-resource-id "${{ env.AZURE_IMAGE }}" \
            --output_path ../.${{ env.DIR }}/cluster.json

      - name: Create A record for master VM
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            RESOURCE_GROUP="ivan-fli-multinode"            
            A_RECORD_NAME="${{ github.job }}"
            MASTER_IP=$(az vm list-ip-addresses -g "EndToEndTest-${{ github.job }}" -n master-vm --query "[].virtualMachine.network.publicIpAddresses[0].ipAddress" -o tsv)

            # Add the A record for the master vm
            az network dns record-set a add-record \
              --resource-group $RESOURCE_GROUP \
              --zone-name ${{ env.ZONE_NAME }} \
              --record-set-name $A_RECORD_NAME \
              --ipv4-address $MASTER_IP  \
              --ttl 3600

      - name: Provision VMs
        run: |
          ./operator/operator-cli/target/release/operator-cli \
            --zarf-package-path ./packages/zarf-package-${{ env.PACKAGE }}-amd64-1.0.0.tar.zst \
            --os-measurement "${{ steps.os_image_info.outputs.OS_MEASUREMENT }}" \
            --platform-measurements-path ./measurements/measurements_azure.json \
            --operator-cert-path ${{ env.DIR }}/certificates/cert.pem \
            --operator-private-key-path ${{ env.DIR }}/certificates/key.pem \
            --cluster-file-path ${{ env.DIR }}/cluster.json \
            --deployment-config-path ${{ env.DIR }}/deployment_config.yaml \
            --attestation-backend "AzureTrustedLaunchVM"

      - name: Build Client app
        run: earthly --strict -P  +client

      - name: Run client app
        run: |

          echo "Wait for DNS to propagate" && sleep 120

          ./multinode-provisioning/examples/client/target/release/client \
            --master-url "https://${{ env.HOSTNAME }}" \
            --operator-certificate-path ${{ env.DIR }}/certificates/cert.pem \
            --bundle-hash "${{ steps.bundle_hash.outputs.BUNDLE_HASH }}" \
            --os-measurement "${{ steps.os_image_info.outputs.OS_MEASUREMENT }}" \
            --platform-measurements-path ./measurements/measurements_azure.json \
            --attestation-backend "AzureTrustedLaunchVM"

      - name: Delete resource group
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group delete -n EndToEndTest --force-deletion-types Microsoft.Compute/virtualMachines --yes
