name: Image push test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  VERSION: 0.0.0-testing-20260125125844

jobs:
  test:
    runs-on: fluorite-runner
    timeout-minutes: 60
    environment: release
    steps:
      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.16

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build attestation-transparency-service and domain-monitor
        run: |
          curl "https://storage.googleapis.com/fluorite/${{ env.VERSION }}/gcp-cvm-notarizer/gcp_notarizer_measurements.json" > libraries/attestation/gcp-shielded-vm-attestation/gcp_notarizer_measurements.json
           

          earthly +attestation-transparency-service
          earthly +domain-monitor
      
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: mycr32671.azurecr.io
          username: mycr32671
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mycr32671.azurecr.io/attestation-transparency-service-image:latest
          file: attestation-transparency-service/Dockerfile

      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mycr32671.azurecr.io/domain-monitor-image:latest
          file: domain-monitor/Dockerfile